# Generated by Django 5.2.8 on 2025-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='plan',
            field=models.CharField(choices=[('free', 'FREE'), ('premium', 'Premium')], default='free', max_length=10, verbose_name='Plano'),
        ),
    ]
