# Generated by Django 5.2.8 on 2025-11-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField(verbose_name='História Gerada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_premium', models.BooleanField(default=False, verbose_name='Versão Premium')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='pets.pet')),
            ],
            options={
                'verbose_name': 'História',
                'verbose_name_plural': 'Histórias',
                'ordering': ['-created_at'],
            },
        ),
    ]
